# Shallow Net Demo in Keras (https://keras.io)

This notebook will cover creating a shallow neural network to clasify MNIST digits.

### MNIST DATASET

MNIST database consists of handwritten digits, which has a training set of 60,000 images, and a test set of 10,000 images. Database was constructed from NIST's Special Database 3 (SD-3) & Special Database 1 (SD-1) which contains digits handwritten by US Census Bureau employees and high-school students, respectively. 

|Training Set|Test Set
-|-|-
**SD-3**|30,000|5,000
**SD-1**|30,000|5,000

#### Setting seed for reproducability

In [1]:
import numpy as np
np.random.seed(10)

#### Import Dependencies

In [2]:
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD

Using TensorFlow backend.


#### What is Dense Layer?

* Each image is **28x28** i.e each image has **784** pixels.

0|1|..........|27
-|-|----------|
28|29|........|55
.|.|..........|
.|.|..........|
.|.|..........|
.|.|..........|**783**

* Flatten the image to create an array of 784 elements. 

0,|1,|2,|......|27,|28,|......|783
-|-|-|-|-|-|-|

![MNIST Flattened](../resources/MNIST-flat.png)

* Flattened array of 784 elements(pixels) above is **INPUT** to our neural net.
* **INPUT LAYER** is fed into **HIDDEN LAYER** to clasify digits into 10 possible classes i.e. 0 to 9 in the **OUTPUT LAYER**.
* A layer is said to be **DENSE or FULLY CONNECTED** when all the neurons of a layer are fully connected to all of the neurons of layer above as well as layer below, as shown in the image below.
* For Eg: In this scenario, if you pick in any neuron in hidden layer, its receiving input from all 784 neurons of input layer and outputing to all 10 neurons of output layer.

![Dense Layer](../resources/Dense.png)

#### Load Data

In [3]:
# Input into a model are typically termed "X" and output that we are trying to guess with the model as "y".
# In this scenario X in array of numbers (pixels) and y is specific label as to what that number is.
# As a practice, matrices as annotated by capital X and y is lower case to annotate 1D array. 

(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [4]:
# Size of training set
# 60,000 digits - all 28x28 images.

X_train.shape

(60000, 28, 28)

In [5]:
y_train.shape

(60000,)

In [6]:
# First hundred digits in training set

y_train[0:99]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4, 3, 5, 3, 6, 1, 7, 2, 8, 6, 9, 4, 0, 9,
       1, 1, 2, 4, 3, 2, 7, 3, 8, 6, 9, 0, 5, 6, 0, 7, 6, 1, 8, 7, 9, 3, 9,
       8, 5, 9, 3, 3, 0, 7, 4, 9, 8, 0, 9, 4, 1, 4, 4, 6, 0, 4, 5, 6, 1, 0,
       0, 1, 7, 1, 6, 3, 0, 2, 1, 1, 7, 9, 0, 2, 6, 7, 8, 3, 9, 0, 4, 6, 7,
       4, 6, 8, 0, 7, 8, 3], dtype=uint8)

In [7]:
# Training data for first digit in training set i.e. number 5.
# This is represented by 28x28 matrix with numerical values for greyscale level.
# 0 depicts white and higher the number, darker the pixel to max value of 255.

X_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [8]:
# Size of test set
# 10,000 digits - all 28x28 images.

X_test.shape

(10000, 28, 28)

In [9]:
y_test.shape

(10000,)

#### Preprocess Data - Training Set
* Change 2D input to 1D array.
* Change Darkness(grayscale level) from 0 to 255 at each pixel to values between 0 to 1.

In [10]:
# Reshaping (training and test) 2D array to 1D array with single point precision.

X_train = X_train.reshape(60000,784).astype('float32')
X_test = X_test.reshape(10000,784).astype('float32')

In [11]:
# Changing darkness to values between 0 and 1.

X_train /= 255
X_test /= 255

In [12]:
# lets look at preprocessed data

X_train[0]

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.  

#### Preprocess Data - Test Set
* Convert y values to one-hot encoding.

if y contains number 2, we want to have it as 

0|0|1|0|0|0|0|0|0|0
-|-|-|-|-|-|-|-|-|-
0|1|**2**|3|4|5|6|7|8|9

if y contains number 5, we want to have it as

0|0|0|0|0|1|0|0|0|0
-|-|-|-|-|-|-|-|-|-
0|1|2|3|4|**5**|6|7|8|9

In [13]:
# Converting numeric representation of digits to one hot encoding.
# n_classes represents number of classes we have to distinguish between.

n_classes = 10
y_train = keras.utils.to_categorical(y_train, n_classes)
y_test = keras.utils.to_categorical(y_test, n_classes)

In [14]:
y_train[0]

array([ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.])

#### Design neural network

* Input Neurons = 784 (flattened 28x28 pixels)
* Hidden Neurons = 64 (This can be any number of choosing)
* Output Neurons = 10 (number of classes to distinguish)

In [15]:
# Using Sequential model as all these layers feed into one another.
model = Sequential()

# Adding Dense hidden and output layer with 64 and 10 neurons, respectively.
model.add(Dense((64),activation='sigmoid',input_shape=(784,)))
model.add(Dense((10),activation='softmax'))

In [16]:
# Viewing the model information
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 64)                50240     
_________________________________________________________________
dense_2 (Dense)              (None, 10)                650       
Total params: 50,890
Trainable params: 50,890
Non-trainable params: 0
_________________________________________________________________


#### Configure model
Before training a model, you need to configure the learning process, which is done via the compile method. It receives three arguments:

* **An optimizer.** This could be the string identifier of an existing optimizer (such as rmsprop or adagrad), or an instance of the Optimizer class. See: optimizers.
* **A loss function.** This is the objective that the model will try to minimize. It can be the string identifier of an existing loss function (such as categorical_crossentropy or mse), or it can be an objective function. See: losses.
* **A list of metrics.** For any classification problem you will want to set this to metrics=['accuracy']. A metric could be the string identifier of an existing metric or a custom metric function.

In [17]:
model.compile(loss='mean_squared_error',optimizer=SGD(lr=0.01),metrics=['accuracy'])

#### Training the model

In [18]:
# epochs is number of iteration
# validation_data is tuple on which to validate loss

model.fit(X_train,y_train,batch_size=128,epochs=200,verbose=1,validation_data=(X_test,y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/200
60000/60000 [==============================] - 1s 15us/step - loss: 0.0949 - acc: 0.0895 - val_loss: 0.0932 - val_acc: 0.0837
Epoch 2/200
60000/60000 [==============================] - 1s 13us/step - loss: 0.0923 - acc: 0.0774 - val_loss: 0.0918 - val_acc: 0.0804
Epoch 3/200
60000/60000 [==============================] - 1s 13us/step - loss: 0.0913 - acc: 0.1055 - val_loss: 0.0910 - val_acc: 0.1385
Epoch 4/200
60000/60000 [==============================] - 1s 13us/step - loss: 0.0906 - acc: 0.1704 - val_loss: 0.0904 - val_acc: 0.1990
Epoch 5/200
60000/60000 [==============================] - 1s 12us/step - loss: 0.0901 - acc: 0.2189 - val_loss: 0.0899 - val_acc: 0.2332
Epoch 6/200
60000/60000 [==============================] - 1s 12us/step - loss: 0.0896 - acc: 0.2453 - val_loss: 0.0894 - val_acc: 0.2546
Epoch 7/200
60000/60000 [==============================] - 1s 12us/step - loss: 0.0892 - acc: 0.2625 - val_loss: 0.0890 - 

60000/60000 [==============================] - 1s 13us/step - loss: 0.0637 - acc: 0.5968 - val_loss: 0.0632 - val_acc: 0.6014
Epoch 60/200
60000/60000 [==============================] - 1s 12us/step - loss: 0.0632 - acc: 0.6019 - val_loss: 0.0627 - val_acc: 0.6061
Epoch 61/200
60000/60000 [==============================] - 1s 12us/step - loss: 0.0628 - acc: 0.6057 - val_loss: 0.0622 - val_acc: 0.6103
Epoch 62/200
60000/60000 [==============================] - 1s 12us/step - loss: 0.0623 - acc: 0.6098 - val_loss: 0.0617 - val_acc: 0.6139
Epoch 63/200
60000/60000 [==============================] - 1s 12us/step - loss: 0.0618 - acc: 0.6143 - val_loss: 0.0613 - val_acc: 0.6186
Epoch 64/200
60000/60000 [==============================] - 1s 12us/step - loss: 0.0614 - acc: 0.6183 - val_loss: 0.0608 - val_acc: 0.6220
Epoch 65/200
60000/60000 [==============================] - 1s 12us/step - loss: 0.0609 - acc: 0.6230 - val_loss: 0.0603 - val_acc: 0.6257
Epoch 66/200
60000/60000 [==============

Epoch 118/200
60000/60000 [==============================] - 1s 12us/step - loss: 0.0428 - acc: 0.7549 - val_loss: 0.0421 - val_acc: 0.7639
Epoch 119/200
60000/60000 [==============================] - 1s 12us/step - loss: 0.0425 - acc: 0.7561 - val_loss: 0.0419 - val_acc: 0.7647
Epoch 120/200
60000/60000 [==============================] - 1s 12us/step - loss: 0.0423 - acc: 0.7566 - val_loss: 0.0416 - val_acc: 0.7655
Epoch 121/200
60000/60000 [==============================] - 1s 12us/step - loss: 0.0421 - acc: 0.7577 - val_loss: 0.0414 - val_acc: 0.7663
Epoch 122/200
60000/60000 [==============================] - 1s 12us/step - loss: 0.0418 - acc: 0.7587 - val_loss: 0.0411 - val_acc: 0.7670
Epoch 123/200
60000/60000 [==============================] - 1s 12us/step - loss: 0.0416 - acc: 0.7598 - val_loss: 0.0409 - val_acc: 0.7682
Epoch 124/200
60000/60000 [==============================] - 1s 13us/step - loss: 0.0414 - acc: 0.7608 - val_loss: 0.0407 - val_acc: 0.7695
Epoch 125/200
60000/

60000/60000 [==============================] - 1s 12us/step - loss: 0.0319 - acc: 0.8386 - val_loss: 0.0311 - val_acc: 0.8470
Epoch 177/200
60000/60000 [==============================] - 1s 12us/step - loss: 0.0318 - acc: 0.8395 - val_loss: 0.0309 - val_acc: 0.8478
Epoch 178/200
60000/60000 [==============================] - 1s 12us/step - loss: 0.0316 - acc: 0.8408 - val_loss: 0.0308 - val_acc: 0.8488
Epoch 179/200
60000/60000 [==============================] - 1s 12us/step - loss: 0.0315 - acc: 0.8415 - val_loss: 0.0307 - val_acc: 0.8496
Epoch 180/200
60000/60000 [==============================] - 1s 12us/step - loss: 0.0314 - acc: 0.8424 - val_loss: 0.0305 - val_acc: 0.8503
Epoch 181/200
60000/60000 [==============================] - 1s 12us/step - loss: 0.0312 - acc: 0.8433 - val_loss: 0.0304 - val_acc: 0.8511
Epoch 182/200
60000/60000 [==============================] - 1s 12us/step - loss: 0.0311 - acc: 0.8439 - val_loss: 0.0303 - val_acc: 0.8517
Epoch 183/200
60000/60000 [=======